#!/bin/bash
echo "This is a test line"
echo "This is second line"
echo "This is third line"
echo "This is fourth line"
echo "This is fifth line"
echo "This is sixth line"
echo "This is the seventh line"
echo "This is the eighth line"
echo "This is the nineth line"
